"ui.background" = { "bg" = "editor-background", fg = "editor-foreground" }
"ui.bufferline" = { "bg" = "background", fg = "#4c5567" }
"ui.bufferline.active" = { "bg" = "editor-background", "fg" = "foreground" }
"ui.highlight.frameline" = { "bg" = "#2C331C" }
"ui.selection" = { "bg" = "#29364D" }
"ui.cursor" = { "bg" = "pink", "fg" = "editor-background" }
"ui.cursor.match" = { underline = { color = "pink", style = "line" } }
"ui.debug.breakpoint" = { fg = "bright-red" }
"ui.debug.active" = { "fg" = "#F9D65B" }
"ui.linenr" = "#4C5669"
"ui.linenr.selected" = "#C6C6C6"
"ui.statusline" = { "bg" = "background", fg = "foreground" }
"ui.statusline.inactive" = { "bg" = "background", "fg" = "#4c5567" }
"ui.statusline.normal" = { "fg" = "green" }
"ui.statusline.insert" = { "fg" = "yellow" }
"ui.statusline.select" = { "fg" = "blue" }
"ui.cursorline.primary" = { "bg" = "#1B2536" }
"ui.virtual.inlay-hint" = { "bg" = "#161E2D", "fg" = "#4C5567" }
"ui.virtual.jump-label" = { "bg" = "#161E2D", "fg" = "editor-foreground" }
"ui.virtual.ruler" = { "bg" = "#161E2D" }
"ui.virtual.indent-guide" = "#212A38"
"ui.virtual.whitespace" = "#212A38"
"ui.virtual.wrap" = "#212A38"
"ui.highlight" = { "bg" = "#1B2536" }
"ui.popup" = { "bg" = "#121926" }
"ui.menu" = { "bg" = "#121926" }
"ui.menu.selected" = { "bg" = "#192333", "fg" = "white" }
"ui.window" = "background"
"info" = { "bg" = "bright-blue-bg", fg = "bright-blue" }
"hint" = { bg = "bright-green-bg", fg = "bright-green" }
"warning" = { "bg" = "bright-yellow-bg", fg = "bright-yellow" }
"error" = { "bg" = "bright-red-bg", fg = "bright-red" }
"diagnostic" = { underline = { color = "bright-green", style = "curl" } }
"diagnostic.info" = { underline = { color = "#358AEC" } }
"diff.delta" = "yellow"
"diff.plus" = "green"
"diff.minus" = "red"
"markup.heading" = "orange"
"markup.heading.1" = { "fg" = "orange", modifiers = [ "bold" ] }
"markup.heading.2" = { "fg" = "orange", modifiers = [ "bold" ] }
"markup.heading.3" = { "fg" = "orange", modifiers = [ "bold" ] }
"markup.bold" = { modifiers = [ "bold" ] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { "bg" = "#161E2D", "fg" = "#4C5567" }
"markup.quote" = { "fg" = "#64727D", modifiers = ["italic"] }
"markup.link.url" = "blue"

"type" = "orange"
"label" = "brown"
"identifier" = "orange"
"constant" = "yellow"
"string" = "green"
"comment" = { "fg" = "#64727D", modifiers = ["italic"] }
"variable" = "pink"
"keyword" = "purple"
"function" = "blue"
"function.builtin" = "turquoise"
"function.macro" = "turquoise"
"namespace" = "orange"
"tag" = "orange"
"attribute" = "yellow"
"constructor" = "orange"

[palette]
black = "#000000"
white = "#FFFFFF"
orange = "#F7987E"
purple = "#B18BB1"
pink = "#EA7599"
yellow = "#EABE9A"
green = "#97A38F"
turquoise = "#7EA9A9"
blue = "#6E94B9"
brown = "#A67868"
red = "#E05252"

bright-blue = "#00B6E3"
bright-blue-bg = "#1E384D"
bright-green = "#73C990"
bright-green-bg = "#2E3030"
bright-yellow = "#FA973B"
bright-yellow-bg = "#312D31"
bright-red = "#FF6464"
bright-red-bg = "#322B3A"

background = "#121926"
foreground = "#99A4B8"
editor-background = "#17202F"
editor-foreground = "#C0C5CE"
highlight = "#99BEFF"
